name: myapp
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+3

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  camera: ^0.11.3+1
  camera_web: ^0.3.0
  onnxruntime: 1.4.1
  image: ^4.2.0
  google_mlkit_face_detection: ^0.13.2
  google_mlkit_text_recognition: ^0.15.1
  google_mlkit_face_mesh_detection: ^0.4.2
  google_mlkit_barcode_scanning: ^0.14.2
  google_mlkit_image_labeling: ^0.14.2
  google_mlkit_object_detection: ^0.15.0
  path_provider: ^2.1.2
  cupertino_icons: ^1.0.8
  cupertino_http: ^2.4.0
  http: ^1.6.0
  flutter_liveness_plugin: ^0.0.8
  facial_liveness_verification: ^2.1.0
  audioplayers: ^5.2.1
  file_picker: ^8.1.4
  video_player: ^2.9.2
  video_thumbnail: ^0.5.6
  flutter_dotenv: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

dependency_overrides:
  permission_handler: ^12.0.1

flutter:
  uses-material-design: true
  
  assets:
    - assets/antispoofing.onnx
    - assets/l2cs_gaze360.onnx
    - .env
